apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hello-world-python-scu4
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hello-world-python-scu4
    app.kubernetes.io/part-of: my-app-3
  name: hello-world-python-scu4
  namespace: jkopriva-tenant
spec:
  path: /
  port:
    targetPort: 8081
  to:
    kind: Service
    name: hello-world-python-scu4
    weight: null
status: {}
